### ISSUE TITLE
ZINC graph edges are directed

### ISSUE THREAD

**Issue by juliuskunze** [chrsmrrs/datasets#4]
All graphs of all 4 ZINC datasets have exclusively directed edges. However, it is mentioned in the [format description](https://chrsmrrs.github.io/datasets/docs/format/) that all graphs are undirected.

It looks like all edges are just meant to be undirected instead of directed, is that correct?

If so, do you plan to update the datasets?

**Comment by chrsmrrs** [comment]
Thanks, I need to check that.

**Comment by juliuskunze** [comment]
@chrsmrrs Thanks!

Btw. is there a reason that default master branch is not synchronized with gh-pages? If you use master privately for something else, I think it would be helpful to make gh-pages the default branch.

That should make it easier to find the content. It was not immediately clear to me that the repo is not empty and the content is on a different branch.

**Comment by chrsmrrs** [comment]
Sorry for taking so long to get back. Yes, indeed, the edges should be undirected. The student converting the dataset made a mistake here. I reached out to her, but she no longer has her scripts.

**Comment by juliuskunze** [comment]
No worries! I invited you to https://github.com/juliuskunze/zinc-undirected which has ZINC dataset ZIP archives with corrected `ZINC_*_A.txt` and `ZINC_*_edge_labels.txt` files. The Python script that I used for the correction is below. Would you mind replacing the ZIP files on your server?

```python3
import os
import sys
from operator import itemgetter

name = sys.argv[1]
A_path = f"{name}/{name}_A.txt"
labels_path = f"{name}/{name}_edge_labels.txt"
A_out = os.path.join(os.path.dirname(A_path),
                     f"{os.path.splitext(os.path.basename(A_path))[0]}_undirected.txt")
labels_out = os.path.join(os.path.dirname(labels_path),
                          f"{os.path.splitext(os.path.basename(labels_path))[0]}_undirected.txt")
with open(A_path, 'r') as A_file, open(labels_path, 'r') as labels_file:
    edges = [tuple(int(x.strip()) for x in l.split(','))
             for l in A_file.readlines()]
    lines = list(zip(edges, labels_file.readlines()))
lines = lines + [(tuple(reversed(nums)), line) for (nums, line) in lines]
lines = sorted(lines, key=itemgetter(0))

with open(A_out, 'w') as A_file, open(labels_out, 'w') as labels_file:
    for ((a, b), l) in lines:
        A_file.write(f"{a},{b}\n")
        labels_file.write(l)
```

**Comment by chrsmrrs** [comment]
Hi Julian,

thanks a lot! I uploaded your fixed ZINC dataset to my server.

Best,
Christopher
