### ISSUE TITLE
Ambiguity in the class labels of MUTAG dataset

### ISSUE THREAD

**Issue by PranavNyati** [chrsmrrs/datasets#7]
Hi @chrsmrrs ,

The class labels for the graphs in MUTAG dataset ([https://www.chrsmrrs.com/graphkerneldatasets/MUTAG.zip](https://www.chrsmrrs.com/graphkerneldatasets/MUTAG.zip)) are either 1 or -1, as per the MUTAG_graph_labels.txt file, but it is not clear from the REDME.txt file of the MUTAG dataset that which one of 1 or -1 represent mutagenic and which one represents non-mutagenic examples. Could you please consider updating the same in the README.txt file for the dataset ?

Moreover, I would like to know what are the discriminatory features of the Mutagenic and Non-Mutagenic examples in the MUTAG dataset, as I am planning to use this dataset for my research in GNN Explainability. Most of the existing explainability papers mention that a higher number of NO2 groups in a molecule is a discriminatory feature for the Mutagenic class;  But when I visualized the graphs for both the classes, I found 1-2 NO2 groups in most molecules of both classes. Hence, it would be great if you could also shed some light in this regard, as to what discriminatory structural features roughly determine whether a molecule should be classified as Mutagenic or Non-Mutagenic as per this dataset.

**Comment by chrsmrrs** [comment]
Hi Pranav, 

Sorry for my late reply. I did not create the MUTAG dataset. To the best of my knowledge, it was https://www2.compute.dtu.dk/~afhar/. Please try reaching out to her.

Best,
Christopher

**Comment by PranavNyati** [comment]
Hi @chrsmrrs,

Thank you for your reply. I am sorry I didn't know this earlier. Thanks again for helping out!

Best,
Pranav
